add ConfirmModel.vue
shared-tw/frontend pull request #11
Opened 2021-06-17 01:25 UTC by jason06286

新增 ConfirmModel.vue
windi.config.ts 有新增顏色 darkblue
為何 hover:bg-darkblue-500 無法顯示效果?

2021-06-17 04:43 UTC, hannoeru requested changes

2021-06-17 04:43 UTC, hannoeru commented on src/components/organisms/ConfirmModel.vue
> +          </button>
```suggestion
          <AppButton class="text-gray-400 border-gray-300 hover:bg-gray-300 hover:text-white" outline>
            取消
          </AppButton>
          <AppButton class="bg-darkblue text-white hover:bg-blue-900">
            提供聯絡資訊
          </AppButton>
```

2021-06-17 04:43 UTC, hannoeru commented on src/components/organisms/ConfirmModel.vue
> +        </div>
這裡可以用 AppCheckbox
你的 base branch 還沒有的樣子
merge 或 rebase main branch 後再加上來

2021-06-17 08:06 UTC, hannoeru commented on src/components/organisms/ConfirmModel.vue
> +          </button>
@jason06286 有一些 class 是可以不用的

2021-06-17 08:43 UTC, hannoeru requested changes

2021-06-17 08:43 UTC, hannoeru commented on src/components/organisms/ConfirmModel.vue
> +          <AppButton class="btn-outline text-gray-400 border-gray-300  hover:bg-gray-300 hover:text-white ">
這邊還是不對，再看一次
https://github.com/shared-tw/frontend/pull/11#discussion_r653218087

2021-06-17 13:43 UTC, hannoeru requested changes

2021-06-17 13:43 UTC, hannoeru commented on t
> +* [33m0fe841e[m chore: init
這個檔案是多餘的吧？

2021-06-17 19:54 UTC, jason06286 commented on t
> +* [33m0fe841e[m chore: init
你是指components.d.ts?還是?我看main 分支上也有

2021-06-17 20:02 UTC, hannoeru commented on t
> +* [33m0fe841e[m chore: init
你新增了 t 這個檔案還把他 commit 上來了

2021-06-17 20:04 UTC, jason06286 commented on t
> +* [33m0fe841e[m chore: init
我理解了!抱歉  我把它刪除了

2021-06-18 06:45 UTC, hannoeru approved these changes

2021-06-18 06:51 UTC, merged